version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:14-alpine
    container_name: fund_postgres_dev
    environment:
      POSTGRES_DB: fund_reports
      POSTGRES_USER: fund_user
      POSTGRES_PASSWORD: fund_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    networks:
      - fund_network_dev
    restart: unless-stopped

  # Redis Cache and Message Broker
  redis:
    image: redis:7-alpine
    container_name: fund_redis_dev
    ports:
      - "6379:6379"
    volumes:
      - redis_data_dev:/data
    networks:
      - fund_network_dev
    restart: unless-stopped
    command: redis-server --appendonly yes

  # MinIO Object Storage
  minio:
    image: minio/minio:latest
    container_name: fund_minio_dev
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data_dev:/data
    networks:
      - fund_network_dev
    restart: unless-stopped
    command: server /data --console-address ":9001"

volumes:
  postgres_data_dev:
  redis_data_dev:
  minio_data_dev:

networks:
  fund_network_dev:
    driver: bridge